blank_issues_enabled: true
contact_links:
  - name: Emby Community forum
    url: https://emby.media/community/
    about: Use the Emby Community forum for general Emby Server support and plugin discussion.
